In [13]:
import tensorflow as tf
import numpy as np

In [4]:
sess = tf.InteractiveSession()


In [6]:
a = tf.placeholder("float", [2, 4])

In [8]:
init = tf.global_variables_initializer()
sess.run(init)

In [18]:
b = tf.reduce_sum(tf.square(a), axis=1, keepdims=True)

In [19]:
b.eval(feed_dict={a:[[1, 2, 3, 4], [6, 7, 8, 9]]})

array([[ 30.],
       [230.]], dtype=float32)

In [27]:
np.shape(b)

TensorShape([Dimension(2), Dimension(1)])

In [21]:
c = tf.reduce_sum(tf.square(tf.transpose(a)), axis=0, keepdims=True)

In [22]:
c.eval(feed_dict={a:[[1, 2, 3, 4], [6, 7, 8, 9]]})

array([[ 30., 230.]], dtype=float32)

In [28]:
np.shape(c)

TensorShape([Dimension(1), Dimension(2)])

In [25]:
d = tf.add(b, c)

In [26]:
d.eval(feed_dict={a:[[1, 2, 3, 4], [6, 7, 8, 9]]})

array([[ 60., 260.],
       [260., 460.]], dtype=float32)

In [29]:
e = -2 * tf.matmul(a, tf.transpose(a))

In [30]:
e.eval(feed_dict={a:[[1, 2, 3, 4], [6, 7, 8, 9]]})

array([[ -60., -160.],
       [-160., -460.]], dtype=float32)

In [31]:
f = d + e

In [32]:
f.eval(feed_dict={a:[[1, 2, 3, 4], [6, 7, 8, 9]]})

array([[  0., 100.],
       [100.,   0.]], dtype=float32)

In [33]:
g = tf.maximum(f, 0)

In [34]:
g.eval(feed_dict={a:[[1, 2, 3, 4], [6, 7, 8, 9]]})

array([[  0., 100.],
       [100.,   0.]], dtype=float32)

In [ ]:
a.eval(feed_dict={a:[[1, 2, 3, 4], [6, 7, 8, 9]]})