In [24]:
import numpy as np
import random

In [3]:
a = np.array([[1 for _ in range(65)] for _ in range(32)])
a

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [21]:
np.shape(a)

(32, 65)

In [17]:
b = np.split(a, [33], 1)


[array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]]), array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])]


In [19]:
b[0]
np.shape(b[0])

(32, 33)

In [22]:
b[1]
np.shape(b[1])

(32, 32)

In [26]:
c = [1 + random.random() for _ in range(32)]
c

[1.9573984527462072,
 1.1121729694684226,
 1.3456653627003354,
 1.8602473184583896,
 1.8910770876336453,
 1.6445932149681886,
 1.2038028354346109,
 1.9846234479688656,
 1.098294392953166,
 1.1721590227225018,
 1.789976590790546,
 1.134671579081961,
 1.2296307034910623,
 1.902599441399078,
 1.1031909020528448,
 1.2764268281898405,
 1.46480810285448,
 1.5245872121621338,
 1.6239903545335646,
 1.0752806715076413,
 1.6181210381675237,
 1.976176977968799,
 1.3077190410265627,
 1.8015664627678485,
 1.912137060491672,
 1.563293739577941,
 1.7373153826798524,
 1.5432108138821174,
 1.5217389056310533,
 1.2270636719939192,
 1.3547854103250896,
 1.0710941631079094]

In [32]:
d = np.expand_dims(c, 1)
d

array([[1.95739845],
       [1.11217297],
       [1.34566536],
       [1.86024732],
       [1.89107709],
       [1.64459321],
       [1.20380284],
       [1.98462345],
       [1.09829439],
       [1.17215902],
       [1.78997659],
       [1.13467158],
       [1.2296307 ],
       [1.90259944],
       [1.1031909 ],
       [1.27642683],
       [1.4648081 ],
       [1.52458721],
       [1.62399035],
       [1.07528067],
       [1.61812104],
       [1.97617698],
       [1.30771904],
       [1.80156646],
       [1.91213706],
       [1.56329374],
       [1.73731538],
       [1.54321081],
       [1.52173891],
       [1.22706367],
       [1.35478541],
       [1.07109416]])

In [37]:
e = b[1] * d
e

array([[1.95739845, 1.95739845, 1.95739845, ..., 1.95739845, 1.95739845,
        1.95739845],
       [1.11217297, 1.11217297, 1.11217297, ..., 1.11217297, 1.11217297,
        1.11217297],
       [1.34566536, 1.34566536, 1.34566536, ..., 1.34566536, 1.34566536,
        1.34566536],
       ...,
       [1.22706367, 1.22706367, 1.22706367, ..., 1.22706367, 1.22706367,
        1.22706367],
       [1.35478541, 1.35478541, 1.35478541, ..., 1.35478541, 1.35478541,
        1.35478541],
       [1.07109416, 1.07109416, 1.07109416, ..., 1.07109416, 1.07109416,
        1.07109416]])

In [43]:
f = np.concatenate([b[0], e], axis=1)
# in tf, tf.concat()
f

array([[1.        , 1.        , 1.        , ..., 1.95739845, 1.95739845,
        1.95739845],
       [1.        , 1.        , 1.        , ..., 1.11217297, 1.11217297,
        1.11217297],
       [1.        , 1.        , 1.        , ..., 1.34566536, 1.34566536,
        1.34566536],
       ...,
       [1.        , 1.        , 1.        , ..., 1.22706367, 1.22706367,
        1.22706367],
       [1.        , 1.        , 1.        , ..., 1.35478541, 1.35478541,
        1.35478541],
       [1.        , 1.        , 1.        , ..., 1.07109416, 1.07109416,
        1.07109416]])

In [44]:
np.shape(f)

(32, 65)