Below are the methods used here.




In [76]:
import tensorflow as tf
import numpy as np

In [12]:
sess = tf.InteractiveSession()

c:\anaconda3\envs\retro\lib\site-packages\tensorflow\python\client\session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [272]:
state = tf.placeholder("float",[None, 4])
w1 = tf.get_variable("asdff", [4, 65])
b1 = tf.get_variable("qweff", [65])
h1 = tf.nn.relu(tf.matmul(state, w1) + b1)

In [273]:
a = h1

In [274]:
a = tf.cast(a, tf.int32)

In [275]:
init = tf.global_variables_initializer()
sess.run(init)

In [276]:
a

<tf.Tensor 'Cast_9:0' shape=(?, 65) dtype=int32>

In [277]:
feed = [[1, 2, 3, 4]] * 32

In [278]:
a.eval(feed_dict={state:feed})

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [279]:
b = tf.shape(a)
b

<tf.Tensor 'Shape_24:0' shape=(2,) dtype=int32>

In [280]:
b.eval(feed_dict={state:feed})

array([32, 65])

In [281]:
b[0].eval(feed_dict={state:feed})

32

In [282]:
c = tf.range(b[0])
c

<tf.Tensor 'range_11:0' shape=(?,) dtype=int32>

In [283]:
c.eval(feed_dict={state:feed})

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [284]:
d = tf.expand_dims(c, axis=1)
d

<tf.Tensor 'ExpandDims_9:0' shape=(?, 1) dtype=int32>

In [285]:
d.eval(feed_dict={state:feed})

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31]])

In [286]:
e = tf.tile(d, (1, 65))
e

<tf.Tensor 'Tile_22:0' shape=(?, 65) dtype=int32>

In [287]:
e.eval(feed_dict={state:feed}) # (32, 65)

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 2,  2,  2, ...,  2,  2,  2],
       ...,
       [29, 29, 29, ..., 29, 29, 29],
       [30, 30, 30, ..., 30, 30, 30],
       [31, 31, 31, ..., 31, 31, 31]])

In [288]:
tf.shape(e) # shape is...

<tf.Tensor 'Shape_25:0' shape=(2,) dtype=int32>

In [290]:
f = tf.stack([e, a], axis=-1) # (32, 65, 2)
f

<tf.Tensor 'stack_14:0' shape=(?, 65, 2) dtype=int32>

In [291]:
f.eval(feed_dict={state:feed})

array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 1,  0],
        [ 1,  0],
        [ 1,  0],
        ...,
        [ 1,  0],
        [ 1,  0],
        [ 1,  0]],

       [[ 2,  0],
        [ 2,  0],
        [ 2,  0],
        ...,
        [ 2,  0],
        [ 2,  0],
        [ 2,  0]],

       ...,

       [[29,  0],
        [29,  0],
        [29,  0],
        ...,
        [29,  0],
        [29,  0],
        [29,  0]],

       [[30,  0],
        [30,  0],
        [30,  0],
        ...,
        [30,  0],
        [30,  0],
        [30,  0]],

       [[31,  0],
        [31,  0],
        [31,  0],
        ...,
        [31,  0],
        [31,  0],
        [31,  0]]])

In [297]:
probs = [0.01] * 65


In [299]:
res = tf.zeros_like(probs)
res

<tf.Tensor 'zeros_like_2:0' shape=(65,) dtype=float32>

In [293]:
#g = tf.scatter_nd(f, )
# um....
# https://www.tensorflow.org/api_docs/python/tf/scatter_nd
# It seems accumulate

<tf.Tensor 'zeros_like:0' shape=(4,) dtype=int32>

In [300]:
asdf.eval()

array([0, 0, 0, 0])